-------------------------------------------------------------------------------
-- This file is to allow you to correct misspellings from the translator.
-- This is not for the feint at heart.
--
-- GS-E uses the enUS dictionary as the master disctionary.  If a word is not
-- translated (comes up red) it means it is missing from the disctionary.  If
-- it is missing completely and not just misspelt you will need to add the reverse
-- for your language
--
-- To use this you need to uncomment the function below. and put the correction
-- pointing to a spellID.
-------------------------------------------------------------------------------

-- -- This function converts an enUS spell name to an ID.
-- GSAvailableLanguages[GSTRStaticHash]["enUS"] = {
-- 	["Ice Flows"] = 108839, -- This should be Ice Floes
-- 	["Lightning Bold"] = 8246, -- This should be Lightening Bolt
-- 	["Eathern Shield Totem"] = 198838,
-- 	["Savage Defense"] = 132402, -- For some reason this comes out as ZZOld
-- }

-- -- This function converts a lowercalse enUS spell name to an ID.
-- GSAvailableLanguages[GSTRStaticShadow]["enUS"] = {
-- 	["ice flows"] = 108839, -- This should be Ice Floes
-- 	["lightning bold"] = 8246, -- This should be Lightening Bolt
-- }

-- -- This function adds a spell to your local language.
-- -- You can override GetLocale() and provide a specific language like "esMX"
-- GSAvailableLanguages[GSTRStaticKey][GetLocale()] = {
-- 	[198838] = ["Escudo Totem"], -- This needs to be the spell name in your language.
-- }
