local L = LibStub("AceLocale-3.0"):NewLocale("GS-E", "ptBR", true)

--Debug Strings from Core
L["createButton PreMacro: "] = "createButton PreMacro: "
L["createButton PostMacro: "] = "createButton PostMacro: "
L["Reloading Sequences"] = "Reloading Sequences"
L["Entering GSSplitMeIntolines with :"] = "Entering GSSplitMeIntolines with :"
L["Line : "] = "Line : "
L["Testing String: "] = "Testing String: "
L[" Deleted Orphaned Macro "] = " Deleted Orphaned Macro "
L["I am loaded"] = "I am loaded"
L[" Sequence named "] = " Sequence named "
L[" is unknown."] = " is unknown."
L["Moving on - "] = "Moving on - "
L[" already exists."] = " already exists."
L["Sequence Name: "] = "Sequence Name: "
L["No Specialisation information for sequence "] = "No Specialisation information for sequence "
L[". Overriding with information for current spec "] = ". Overriding with information for current spec "
L["Checking if specID "] = "Checking if specID "
L[" equals "] = " equals "
L[" equals currentclassid "] = " equals currentclassid "
L["GSUpdateSequence PreMacro updated to: "] = "GSUpdateSequence PreMacro updated to: "
L["GSUpdateSequence PostMacro updated to: "] = "GSUpdateSequence PostMacro updated to: "
L["Adding missing Language :"] =  "Adding missing Language :"

--Debug Strings from Errorhandler
L["Dump of GS Debug messages"] = "Dump of GS Debug messages"
L["Update"] = "Update"
L["Close"] = "Close"
L["[GNOME] syntax error on line %d of Sequences.lua:|r %s"] = "[GNOME] syntax error on line %d of Sequences.lua:|r %s"
L["<SEQUENCEDEBUG> |r "] = "<SEQUENCEDEBUG> |r "
L["<DEBUG> |r "] = "<DEBUG> |r "

--Output Strings from Core
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = "Close to Maximum Personal Macros.|r  You can have a maximum of "
L[" macros per character.  You currently have "] = " macros per character.  You currently have "
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = "|r.  As a result this macro was not created.  Please delete some macros and reenter "
L["/gs|r again."] = "/gs|r again."
L["Close to Maximum Macros.|r  You can have a maximum of "] = "Close to Maximum Macros.|r  You can have a maximum of "
L["|r.  You can also have a  maximum of "] = "|r.  You can also have a  maximum of "
L[" macros per Account.  You currently have "] = " macros per Account.  You currently have "
L["Contributed by: "] = "Contributed by: "
L["No Help Information "] = "No Help Information "
L["Unknown Author|r "] = "Unknown Author|r "
L["|r Incomplete Sequence Definition - This sequence has no further information "] = "|r Incomplete Sequence Definition - This sequence has no further information "

-- Setup and Help Output from Core
L[":|r GnomeSequencer was originally written by semlar of wowinterface.com."] = ":|r GnomeSequencer was originally written by semlar of wowinterface.com."
L[":|r This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = ":|r This is a small addon that allows you create a sequence of macros to be executed at the push of a button."
L[":|r Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = ":|r Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."
L[":|r This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = ":|r This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."
L[":|r To get started "] = ":|r To get started "
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = "/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."
L["/gs listall|r will produce a list of all available macros with some help information."] = "/gs listall|r will produce a list of all available macros with some help information."
L[":|r To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = ":|r To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."
L[":|r The command "] = ":|r The command "
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = "/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = "/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."
L[":|r Your current Specialisation is "] = ":|r Sua especialização atual é "
L["  The Alternative ClassID is "] = "  O ClassID alternativa é "
L["GnomeSequencer-Enhanced loaded.|r  Type "] = "GnomeSequencer-Enhanced carregado.|r  Digitar "
L["/gs help|r to get started."] = "/gs help|r to get started."
L["Version="] = "Versão="
L[":|r You cannot delete the only copy of a sequence."] = "Você não pode excluir a única cópia de uma sequência."
