local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "zhCN", true)

-- Options translation
L["  The Alternative ClassID is "] = "  选择的职业ID "
L[" already exists."] = " 已经存在."
L[" Deleted Orphaned Macro "] = " 删除孤立的宏 "
L[" equals "] = " 等于 "
L[" equals currentclassid "] = " 等于当前职业ID "
L[" from "] = " 从 "
L[" From library"] = " 从库"
L[" has been added as a new version and set to active.  Please review if this is as expected."] = " 已经添加为新版本并设置为活动的.请检查以保障这是你预期的设置."
L[" is not available.  Unable to translate sequence "] = " 无法使用.因为无法翻译该序列. "
L[" is unknown."] = " 是未知的."
L[" macros per Account.  You currently have "] = " 宏/账户.你目前已有 "
L[" macros per character.  You currently have "] = " 宏/角色.你目前已有 "
L[" not added to list."] = " 未添加至列表."
L[" saved as version "] = " 保存至版本 "
L[" sent"] = " 发送"
L[" Sequence named "] = " 命名序列 "
L[" tried to overwrite the version already loaded from "] = " 试图覆盖已经加载的版本 "
L[" was imported with the following errors."] = " 导入时出现以下错误."
L[" with iconid "] = " 设置(with)图标ID "
L[". Overriding with information for current spec "] = ". 覆盖当前的天赋信息 "
L[". This version was not loaded."] = ". 未加载此版本."
L["/gs |r to get started."] = "/gs |r 以开始."
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = "/gs cleanorphans|r 将遍历你的宏删除任何GS-E宏使其不再有任何序列匹配."
L["/gs help|r to get started."] = "/gs help|r 获取上手指南."
L["/gs listall|r will produce a list of all available macros with some help information."] = "/gs listall|r 将列出所有可用的宏和一些帮助信息."
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = "/gs showspec|r 显示你使用的天赋ID以及专精信息和特定标签任何现有的宏."
L["/gs|r again."] = "/gs|r 再一次."
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = "/gs|r 将列出所有当前天赋的宏.同样添加全部你当前天赋的宏到宏界面."
L["/gsse |r to get started."] = "/gsse |r 获取上手指南."
L[":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"] = ":|r 序列翻译允许你使用英语之外的其他语言在gs-e上.它将翻译序列来匹配你的语言.如果你也有序列编辑器,你可以在不同语言之间翻译序列.gs-e序列的翻译可在curse.com找到"
L[":|r To get started "] = ":|r 获取上手指南 "
L[":|r You cannot delete the only copy of a sequence."] = ":|r 你不能删除序列的唯一副本."
L[":|r Your current Specialisation is "] = ":|r 你现在的专精是 "
L["[GNOME] syntax error on line %d of Sequences.lua:|r %s"] = "[GNOME] 语法错误在Sequences.lua的第 %d 行 :|r %s"
L["], (GSisEmpty(GSMasterOptions.SequenceLibrary["] = "], (GSisEmpty(GSMasterOptions.SequenceLibrary["
L["].lang or GetLocale()), key)"] = "].lang 或 GetLocale()), key)"
L["].lang) and GSMasterOptions.SequenceLibrary["] = "].lang) 和 GSMasterOptions.SequenceLibrary["
L["|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"] = "|cffff0000GS-E:|r Gnome Sequencer - Enhanced 设置"
L["|r Incomplete Sequence Definition - This sequence has no further information "] = "|r 不完整序列定义 - 此序列没有其他信息 "
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = "|r.  所以此宏未创建. 请删除一些宏并重新输入 "
L["|r.  You can also have a  maximum of "] = "|r.  同时你最多可以拥有 "
L["<DEBUG> |r "] = "<DEBUG> |r "
L["<SEQUENCEDEBUG> |r "] = "<SEQUENCEDEBUG> |r "
L["A sequence colision has occured. "] = "发生了一个序列冲突. "
L["A sequence collision has occured. "] = "发生了一个序列冲突. "
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = "发生了一个序列冲突.  已加载此宏的其他版本.  管理序列器以确认如何使用它们 "
L["A sequence collision has occured.  Your local version of "] = "发生了一个序列冲突.   你的本地版本 "
L["Actions"] = "动作"
L["Active Version "] = "活动版本 "
L["Active Version: "] = "活动版本: "
L[ [=[Addin Version %s contained versions for the following macros:
%s]=] ] = [=[添加版本 %s 包含版本于下列宏: 
%s]=]
L["Adding missing Language :"] = "添加缺少的语言 :"
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = "你确定要删除 %s?  这将删除改宏和所有版本.  本操作无法撤销."
L["As GS-E is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gs cleanorphans"] = "GS-E已更新,可能会有遗留的不再使用的宏. 登出时会自动检查. 另外这个检查可以通过输入 / GS cleanorphans 运行."
L["Author"] = "作者"
L["Author Colour"] = "作者颜色"
L["Auto Create Class Macro Stubs"] = "自动创建职业宏存根"
L["Auto Create Global Macro Stubs"] = "自动创建全局宏存根"
L["Available Addons"] = "可用插件"
L["Belt"] = "腰带"
L["Blizzard Functions Colour"] = "暴雪功能颜色"
L["By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."] = "通过设置宏的图标为问号, 使宏在每次按下时变更图标."
L["By setting this value the Sequence Editor will show every macro for every class."] = "设置这个值,插件将显示全部职业的全部宏."
L["By setting this value the Sequence Editor will show every macro for your class."] = "设置这个值,插件将显示当前职业的全部宏."
L["Cancel"] = "撤销/取消"
L["Checking if specID "] = "检查如果天赋ID "
L["Choose Language"] = "选择语言"
L["Class = "] = "职业 = "
L["Classwide Macro"] = "职业通用宏"
L["Clear"] = "清除"
L["Clear Errors"] = "清除错误"
L["Close"] = "关闭"
L["Close to Maximum Macros.|r  You can have a maximum of "] = "超过最大宏上限.|r  你最多可以有 "
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = "超过最大角色宏上限.|r  你最多可以有 "
L["Colour"] = "颜色"
L["Colour and Accessibility Options"] = "颜色和辅助功能设置"
L["Combat"] = "战斗"
L["Command Colour"] = "命令颜色"
L["Completely New GS Macro."] = "全新的GS宏."
L["Conditionals Colour"] = "条件颜色"
L["Configuration"] = "结构"
L["Contributed by: "] = "贡献者: "
L["Copy this link and open it in a Browser."] = "复制此链接并在浏览器中打开它."
L["Create Icon"] = "创建图标"
L["Create Macro"] = "创建宏"
L["createButton PostMacro: "] = "创建按钮在宏主体之后: "
L["createButton PreMacro: "] = "创建按钮在宏主体之前: "
L["Creating New Sequence."] = "创建新序列."
L["Cycle Version "] = "循环版本 "
L["Debug"] = "调试"
L["Debug Mode Options"] = "调试模式设置"
L["Debug Output Options"] = "调试输出设置"
L["Debug Sequence Execution"] = "调试序列执行"
L["Default Version"] = "默认版本"
L["Delete"] = "删除"
L["Delete Icon"] = "删除图标"
L["Delete Orphaned Macros on Logout"] = "登出时删除孤立的宏"
L["Delete Version"] = "删除版本"
L["Different helpTxt"] = "不同的帮助脚本"
L["Different PostMacro"] = "不同的宏主体之后"
L["Different PreMacro"] = "不同的前期宏"
L["Different Sequence Steps"] = "不同的序列步骤"
L["Different specID"] = "不同的天赋ID"
L["Different StepFunction"] = "不同的步骤方法"
L["Disable"] = "禁用"
L["Disable Sequence"] = "禁用序列"
L["Display debug messages in Chat Window"] = "在聊天窗口中显示调试信息"
L["Dump of GS Debug messages"] = "转存GS调试信息"
L["Edit"] = "编辑"
L["Editor Colours"] = "编辑器颜色"
L["Emphasis Colour"] = "强调颜色"
L["Enable"] = "启用"
L["Enable Debug for the following Modules"] = "启用调试给以下模块"
L["Enable Mod Debug Mode"] = "启用模块调试模式"
L["Enable Sequence"] = "启用宏"
L["Entering GSSplitMeIntolines with :"] = "进入 GSSplitMeIntolines 以 :"
L["Export"] = "导出"
L["Export a Sequence"] = "导出序列"
L["Filter Macro Selection"] = "宏过滤选择器"
L["FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "F你不能删除此版本的序列.这个版本将被重新加载,因为它包含在 "
L["Gameplay Options"] = "游戏选项"
L["GCD Delay:"] = "公共CD延迟:"
L["General"] = "常规"
L["General Options"] = "常规设置"
L["Gnome Sequencer: Export a Sequence String."] = "Gnome Sequencer: 输出序列字符串."
L["Gnome Sequencer: Import a Macro String."] = "Gnome Sequencer: 导入宏字符串."
L["Gnome Sequencer: Record your rotation to a macro."] = "Gnome Sequencer: 记录你的循环到一个宏."
L["Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"] = "Gnome Sequencer: 序列调试. 监视你的宏的执行"
L["Gnome Sequencer: Sequence Editor."] = "Gnome Sequencer: 序列编辑器."
L["Gnome Sequencer: Sequence Version Manager"] = "Gnome Sequencer: 序列版本管理器"
L["Gnome Sequencer: Sequence Viewer"] = "Gnome Sequencer: Sequence Viewer"
L["GnomeSequencer was originally written by semlar of wowinterface.com."] = "GnomeSequencer最初是由wowinterface.com的semlar编写的."
L["GnomeSequencer-Enhanced"] = "GnomeSequencer-增强"
L["GnomeSequencer-Enhanced loaded.|r  Type "] = "GnomeSequencer-增强 加载.|r  输入 "
L["GSE"] = "GSE"
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = "GSE允许插件加载宏整合包作为插件. 你可以按下面的按钮重新加载整合包."
L["GS-E can save all macros or only those versions that you have created locally.  Turning this off will cache all macros in your WTF\\GS-Core.lua variables file but will increase load times and potentially cause colissions."] = "GS-E可以保存所有的宏或只有那些你所创建的本地版本.关闭这个功能会在你的WTF \\ gs-core.lua变量文件缓存所有宏,但会增加加载时间,并有可能引起冲突."
L["GS-E is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = "GS-E 已过期. 你可以在 https://mods.curse.com/addons/wow/gnomesequencer-enhanced 下载新版本."
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = "GSE 已过期. 你可以在  https://mods.curse.com/addons/wow/gnomesequencer-enhanced 下载新版本."
L["GSE Macro"] = "GSE 宏"
L["GS-E Plugins"] = "GS-E 插件"
L["GS-E: Left Click to open the Sequence Editor"] = "GS-E: 左键单击以打开序列编辑器"
L["GS-E: Middle Click to open the Transmission Interface"] = "GS-E: 中键单击以打开传输界面"
L["GS-E: Right Click to open the Sequence Debugger"] = "GS-E: 右键单击以打开序列调试器"
L["GSSE:loadSequence "] = "GSSE:读取序列 "
L["GSTranslateSequenceFromTo(GSMasterOptions.SequenceLibrary["] = "GSTranslateSequenceFromTo(GSMasterOptions.SequenceLibrary["
L["GSUpdateSequence PostMacro updated to: "] = "GSUpdateSequence 宏主体之后更新为: "
L["GSUpdateSequence PreMacro updated to: "] = "GSUpdateSequence 宏主体之前更新为: "
L["has been disabled.  The Macro stub for this sequence will be deleted and will not be recreated until you re-enable this sequence.  It will also not appear in the /gs list until it is recreated."] = "已经禁用.来自该序列的宏存根将被删除并且不会重建,直到你再次启用该序列.同样它不会显示在/gs list的列表里直到你再次启用该序列."
L["has been enabled.  The Macro stub is now available in your Macro interface."] = "已经启用.该宏存根现在会显示在你的宏界面."
L["Head"] = "头部"
L["Help Colour"] = "帮助颜色"
L["Help Information"] = "帮助信息"
L["Help Link"] = "帮助链接"
L["Help URL"] = "帮助网址"
L["I am loaded"] = "我是加载"
L["Icon Colour"] = "图标颜色"
L["Icon: "] = "图标: "
L["If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."] = "如果你加载 Gnome Sequencer - Enhanced(侏儒序列器-增强) 和 Sequence Editor(序列编辑器) 并希望从头开始创建新的宏, 这将启用一个初始序列模板,你可以加载到编辑器作为起点.  它会启动一个名为Draik01的宏作为Hellow World宏.  你需要输入 /console reloadui 之后使之生效."
L["Import"] = "导入"
L["Import Macro from Forums"] = "从论坛导入宏"
L["Imported new sequence "] = "导入新序列 "
L["Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."] = "使用腰部在释放按键时. 这等效于 /use [combat] 5 在释放按键时."
L["Incorporate the belt slot into the PostMacro. This is the equivalent of /use [combat] 5 in a PostMacro."] = "使用腰部在宏主体之后. 这等效于 /use [combat] 5 在宏主体之后."
L["Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."] = "使用第一个戒指在释放按键时. 这等效于 /use [combat] 11 在释放按键时."
L["Incorporate the first ring slot into the PostMacro. This is the equivalent of /use [combat] 11 in a PostMacro."] = "使用第一个戒指在宏主体之后. 这等效于 /use [combat] 11 在宏主体之后."
L["Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."] = "使用第一个饰品在释放按键时. 这等效于 /use [combat] 13 在释放按键时."
L["Incorporate the first trinket slot into the PostMacro. This is the equivalent of /use [combat] 13 in a PostMacro."] = "使用第一个饰品在宏主体之后. 这等效于 /use [combat] 13 在宏主体之后."
L["Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."] = "使用头部在释放按键时. 这等效于 /use [combat] 1在释放按键时."
L["Incorporate the Head slot into the PostMacro. This is the equivalent of /use [combat] 1 in a PostMacro."] = "使用头部在宏主体之后. 这等效于 /use [combat] 1 在宏主体之后."
L["Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."] = "使用颈部在释放按键时. 这等效于 /use [combat] 2在释放按键时."
L["Incorporate the neck slot into the PostMacro. This is the equivalent of /use [combat] 2 in a PostMacro."] = "使用颈部在宏主体之后. 这等效于 /use [combat] 2 在宏主体之后."
L["Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."] = "使用第二个戒指在释放按键时. 这等效于 /use [combat] 12 在释放按键时."
L["Incorporate the second ring slot into the PostMacro. This is the equivalent of /use [combat] 12 in a PostMacro."] = "使用第二个戒指在宏主体之后. 这等效于 /use [combat] 12 在宏主体之后."
L["Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."] = "使用第二个饰品在释放按键时. 这等效于 /use [combat] 14 在释放按键时."
L["Incorporate the second trinket slot into the PostMacro. This is the equivalent of /use [combat] 14 in a PostMacro."] = "使用第二个饰品在宏主体之后. 这等效于 /use [combat] 14 在宏主体之后."
L["Inner Loop End"] = "内部循环结束"
L["Inner Loop Limit"] = "内部循环限制"
L["Inner Loop Start"] = "内部循环开始"
L["is currently disabled from use."] = "目前禁止使用."
L["KeyPress"] = "按键按下"
L["KeyRelease"] = "按键释放"
L["Language"] = "语言"
L["Language Colour"] = "语言颜色"
L["Legacy GS/GSE1 Macro"] = "遗留的 GS/GSE1 宏"
L["Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = "像一个 /castsequence 宏, 它在按下按钮时循环执行一系列命令. 然而, 与 /castsequence 不同, 它严格使用宏文本作为命令而不是根据法术状态, 并且它每次按下按钮时都会前进而不在它不能释放时停止."
L["Line : "] = "线 : "
L["Load"] = "读取"
L["Load Sequence"] = "读取序列"
L["Macro Collection to Import."] = "宏集合导入."
L["Macro Found "] = "宏找到 "
L["Macro Icon"] = "宏图标"
L["Macro Import Successful."] = "宏导入成功."
L["Macro unable to be imported."] = "无法导入宏."
L["Macro Version %d deleted."] = "宏版本%d 已删除."
L["Make Active"] = "使它活动"
L["Manage Versions"] = "管理版本"
L["Matching helpTxt"] = "匹配帮助文本"
L["Matching PostMacro"] = "匹配宏主体之后"
L["Matching PreMacro"] = "匹配宏主体之前"
L["Matching specID"] = "匹配天赋ID"
L["Matching StepFunction"] = "匹配步骤方法"
L["Moving on - "] = "继续 - "
L["Moving on - LiveTest.PosMacro already exists."] = "继续 - LiveTest.PosMacro 已经存在."
L["Moving on - LiveTest.PreMacro already exists."] = "继续 - LiveTest.PreMacro 已经存在."
L["Moving on - macro for "] = "继续 - 宏为 "
L["Mythic"] = "史诗使用版本"
L["Neck"] = "颈部"
L["New"] = "新"
L["No"] = "否"
L["No Active Version"] = "无活动版本"
L["No Help Information "] = "无帮助信息 "
L["No Help Information Available"] = "没有帮助信息可用"
L["No Macro Found. Possibly different spec for Sequence "] = "找不到宏. 也许序列天赋不同 "
L["No Sequence Icon setting to "] = "无序列图标设置为 "
L["No Sequences present so none displayed in the list."] = "当前没有序列,因此列表中无内容."
L["No Specialisation information for sequence "] = "没有序列的专精信息 "
L["No value"] = "无值"
L["none"] = "没有	"
L["Normal Colour"] = "通常颜色"
L["of no value"] = "没有值"
L["Only Save Local Macros"] = "仅保存本地宏"
L["Options"] = "设置"
L["Output"] = "导出"
L["Output the action for each button press to verify StepFunction and spell availability."] = "输出按钮按下后的每个的动作以验证步骤方法和法术的可用性."
L["Pause"] = "暂停"
L["Picks a Custom Colour for emphasis."] = "拾取一个颜色给强调."
L["Picks a Custom Colour for the Author."] = "拾取一个颜色给作者."
L["Picks a Custom Colour for the Commands."] = "拾取一个颜色给命令."
L["Picks a Custom Colour for the Mod Names."] = "拾取一个颜色给MOD名称."
L["Picks a Custom Colour to be used for braces and indents."] = "选择要使用的自定义颜色给框架和缩进."
L["Picks a Custom Colour to be used for Icons."] = "选择要使用的自定义颜色给图标."
L["Picks a Custom Colour to be used for language descriptors"] = "选择要使用的自定义颜色给语言描述"
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = "选择要使用的自定义颜色给宏按键条件,如:[mod:shift]"
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = "选择要使用的自定义颜色给宏关键字,如: /cast 和 /target"
L["Picks a Custom Colour to be used for numbers."] = "选择要使用的自定义颜色给数字."
L["Picks a Custom Colour to be used for Spells and Abilities."] = "选择要使用的自定义颜色给法术和技能."
L["Picks a Custom Colour to be used for StepFunctions."] = "选择要使用的自定义颜色给步骤方法."
L["Picks a Custom Colour to be used for strings."] = "选择要使用的自定义颜色给字符串."
L["Picks a Custom Colour to be used for unknown terms."] = "选择要使用的自定义颜色给未知术语."
L["Picks a Custom Colour to be used normally."] = "选择要使用的自定义颜色给常用颜色."
L["Please wait till you have left combat before using the Sequence Editor."] = "请等待离开战斗后再使用序列编辑器."
L["Plugins"] = "插件"
L["PostMacro"] = "宏主体之后"
L["PreMacro"] = "宏主体之前"
L["Prevent Sound Errors"] = "防止错误音效"
L["Prevent UI Errors"] = "防止错误提示"
L["Priority List (1 12 123 1234)"] = "优先级列表 (1 12 123 1234)"
L["PVP"] = "PVP使用版本"
L["PVP setting changed to Default."] = "PVP设置更改为默认值."
L["Raid"] = "Raid使用版本"
L["Ready to Send"] = "准备发送"
L["Received Sequence "] = "接收序列 "
L["Record"] = "记录"
L["Record Macro"] = "记录宏"
L["Registered Addons"] = "注册插件"
L["Reloading Sequences"] = "重新加载序列"
L["Removing "] = "删除 "
L["Require Target to use"] = "需要使用目标"
L["Reset Macro when out of combat"] = "当离开战斗时重置宏"
L["Resets"] = "重置"
L["Resets macros back to the initial state when out of combat."] = "在退出战斗时宏重置为初始状态."
L["Resume"] = "恢复"
L["Ring 1"] = "戒指 1"
L["Ring 2"] = "戒指 2"
L["Same Sequence Steps"] = "相同的序列步骤"
L["Save"] = "保存"
L["Seed Initial Macro"] = "种子初始宏"
L["Select Other Version"] = "选择其他版本"
L["Selecting tab: "] = "选择标签: "
L["Send"] = "发送"
L["Send To"] = "发送至"
L["Sequence"] = "序列(宏主体)"
L["Sequence %s saved."] = "序列 %s 以保存."
L["Sequence Author set to Unknown"] = "序列作者设置为未知"
L["Sequence Debugger"] = "序列调试器"
L["Sequence Editor"] = "序列编辑器"
L["Sequence Name"] = "序列名"
L["Sequence Name: "] = "序列名: "
L["Sequence Saved as version "] = "保存序列版本为 "
L["Sequence specID set to current spec of "] = "序列天赋ID设置为当前天赋 "
L["Sequence Viewer"] = "序列查看器"
L["sequenceIndex: "] = "序列索引: "
L["SequenceSpecID: "] = "序列天赋ID: "
L["Sequential (1 2 3 4)"] = "顺序 (1 2 3 4)"
L["Set Default Icon QuestionMark"] = "设置默认图标为问号"
L["Setting Editor clean "] = "设置编辑器清理 "
L["Show All Macros in Editor"] = "在编辑器显示全部宏"
L["Show Class Macros in Editor"] = "在编辑器显示职业宏"
L["Source "] = "源 "
L["Source Language "] = "源语言 "
L["Spec = "] = "天赋 = "
L["Specialisation / Class ID"] = "专精 / 职业 ID"
L["Specialization Specific Macro"] = "专精特定宏"
L["SpecID/ClassID Colour"] = "天赋ID/职业ID 颜色"
L["Spell Colour"] = "法术颜色"
L["Step Function"] = "步骤方法"
L["Step Functions"] = "步骤方法"
L["Stop"] = "停止"
L["Store Debug Messages"] = "储存调试消息"
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = "将调试消息的输出存储在可由其他mod引用的全局变量中."
L["String Colour"] = "字符串颜色"
L["String Icon "] = "字符串图标 "
L["Talents"] = "天赋"
L["Target"] = "目标"
L["Target language "] = "目标语言 "
L["Testing "] = "测试 "
L["Testing String: "] = "测试字符串: "
L["The command "] = "命令 "
L["The Custom StepFunction Specified is not recognised and has been ignored."] = "指定的自定义步骤方法无法识别,并已被忽略."
L["The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."] = "宏翻译器将英语序列翻译成你的本地语言以供执行. 它也可以用于将序列翻译成不同的语言. 同时可用于编辑器中基于语法的颜色标记."
L["The Sample Macros have been reloaded."] = "示例宏已重新加载."
L["The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."] = "序列编辑器可以尝试实时解析序列,按键按下/释放.这仍然是实验功能所以可以关闭."
L["The Sequence Editor can attempt to parse the Sequences, PreMacro and PostMacro in realtime.  This is still experimental so can be turned off."] = "序列编辑器可以尝试实时解析序列,宏主体之前/后.这仍然是实验功能所以可以关闭."
L["The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "] = "序列编辑器是 GnomeSequencer-增强 的插件,允许你在游戏中查看和编辑序列.  输入 "
L["There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"] = "这个职业没有任何宏. 你要加载示例宏吗?"
L["This change will not come into effect until you save this macro."] = "此更改将不会生效,直到你保存此宏."
L["This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = "这是一个小插件,允许你创建一个宏序列以便在按下按钮时执行."
L["This is the only version of this macro.  Delete the entire macro to delete this version."] = "这是此宏的唯一版本. 删除整个宏以删除此版本."
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "该选项会清除游戏中的错误追踪.这等于写入 /run UIErrorsFrame:Clear() 在按键释放.  打开这个将触发一个关于运行自定义脚本的欺骗警告."
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."] = "该选项会清除游戏中的错误追踪.这等于写入 /run UIErrorsFrame:Clear() 在宏主体之后.  打开这个将触发一个关于运行自定义脚本的欺骗警告."
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = "此选项将额外的跟踪信息转储到聊天窗口,以帮助解决模块的问题"
L["This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."] = "该选项将隐藏当你使用GS宏时的\"超出范围了\"之类的音效.等于命令 /console Sound_EnableErrorSpeech.打开这个将触发一个关于运行自定义脚本的欺骗警告."
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "该选项僵隐藏错误文本弹出和对话框和堆栈跟踪.这等于写入 /script UIErrorsFrame:Hide() 在按键释放.  打开这个将触发一个关于运行自定义脚本的欺骗警告."
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."] = "该选项僵隐藏错误文本弹出和对话框和堆栈跟踪.这等于写入 /script UIErrorsFrame:Hide() 在宏主体之后.  打开这个将触发一个关于运行自定义脚本的欺骗警告."
L["This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."] = "该选项将禁止你在没有目标的时候启动宏.有助于减少当你的目标死亡时错误的针对其他怪物/组."
L["This Sequence is currently Disabled Locally."] = "This Sequence is currently Disabled Locally."
L["This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = "这个版本已经被TimothyLuke修改,使GnomeSequencer的强大功能可以让不习惯lua编程的人使用."
L["This will display debug messages for the "] = "这将显示调试消息 "
L["This will display debug messages for the Core of GS-E"] = "这将显示GS-E核心的调试消息"
L["This will display debug messages for the GS-E Ingame Transmission and transfer"] = "这将显示GS-E在游戏内传输和转移的调试消息"
L["This will display debug messages for the GS-E Sequence Editor"] = "这将显示GS-E序列编辑器的调试消息"
L["This will display debug messages for the GS-E Translator"] = "这将显示GS-E翻译的调试消息"
L["This will display debug messages in the Chat window."] = "这将在聊天窗口显示调试消息."
L["Title Colour"] = "标题颜色"
L["To get started "] = "获取上手指南 "
L["To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = "要使用宏,请打开宏界面,并创建一个与列表中名称完全相同的宏. 一个具有两行的新宏将被创建,将其放在你的操作栏上."
L["Translate to"] = "翻译至"
L["Translated Sequence"] = "翻译序列"
L["Trinket 1"] = "饰品 1"
L["Trinket 2"] = "饰品 2"
L["Two sequences with unknown sources found."] = "找到两个未知来源的序列."
L["Unknown Author|r "] = "未知作者|r "
L["Unknown Colour"] = "未知颜色"
L["Update"] = "更新"
L["Updating due to new version."] = "更新至新版本."
L["Use"] = "使用"
L["Use Belt Item in KeyRelease"] = "使用腰部物品在释放按键"
L["Use Belt Item in Postmacro"] = "使用腰部物品在宏主体之后"
L["Use First Ring in KeyRelease"] = "使用第一个戒指在释放按键"
L["Use First Ring in Postmacro"] = "使用第一个戒指在宏主体之后"
L["Use First Trinket in KeyRelease"] = "使用第一个饰品在释放按键"
L["Use First Trinket in Postmacro"] = "使用第一个饰品在宏主体之后"
L["Use Global Account Macros"] = "使用全局账户宏"
L["Use Head Item in KeyRelease"] = "使用头部物品在释放按键"
L["Use Head Item in Postmacro"] = "使用头部物品在宏主体之后"
L["Use Macro Translator"] = "使用宏翻译器"
L["Use Neck Item in KeyRelease"] = "使用颈部物品在释放按键"
L["Use Neck Item in Postmacro"] = "使用颈部物品在宏主体之后"
L["Use Realtime Parsing"] = "使用实时解析"
L["Use Second Ring in KeyRelease"] = "使用第二个戒指在释放按键"
L["Use Second Ring in Postmacro"] = "使用第二个戒指在宏主体之后"
L["Use Second Trinket in KeyRelease"] = "使用第二个饰品在释放按键"
L["Use Second Trinket in Postmacro"] = "使用第二个饰品在宏主体之后"
L["Version="] = "版本="
L["We have a perfect match"] = "我们有一个完美的匹配"
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = "创建宏时,如果没有角色宏空间,创建帐户通用的宏."
L["When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"] = "加载或创建序列时,如果它是全局宏或宏具有未知的天赋ID,则会自动在帐户宏中创建宏存根"
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = "当加载或创建序列时,如果它是同职业的宏,则自动创建宏存根"
L["with no body"] = "没有主体"
L["Yes"] = "是"
L["You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."] = "你不能删除此宏的默认版本. 请选择另一个版本作为配置选项卡上的默认值."
L["You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "你不能删除此版本的序列. 此版本将重新加载,因为它包含在 "
L["You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"] = "你需要重新加载用户界面以使步骤方法中的更改生效. 你现在想这样做吗?"
L["You need to reload the User Interface to complete this task.  Would you like to do this now?"] = "你需要重新加载用户界面以完成此任务. 你现在想这样做吗?"
L["Your current Specialisation is "] = "你当前的专精是 "
----GSE2.0.1-2.0.4
L["Create buttons for Global Macros"] = "创建全局宏的按钮"
L["Global Macros are those that are valid for all classes.  GSE2 also imports unknown macros as Global.  This option will create a button for these macros so they can be called for any class.  Having all macros in this space is a performance loss hence having them saved with a the right specialisation is important."] = "全局宏是对所有职业都有效的宏.GSE2也导入未知的全局宏.此选项将创建一个按钮使它们可以被任何职业调用.所有宏存在这个空间都会有性能损失.因此最好把它们保存在正确的专精下."
L["Show Global Macros in Editor"] = "在编辑器显示全局宏"
L["This shows the Global Macros available as well as those for your class."] = "这将显示你当前职业可用的全局宏."
L["Moved %s to class %s."] = "移动 %s 到职业 %s. "
L["Your current Specialisation is "] = "你当前的专精是"
L["Hide Login Message"] = "隐藏加载信息"
L["Hides the message that GSE is loaded."] = "隐藏GSE加载的信息"




L["Update"] = true
L["<SEQUENCEDEBUG> |r "] = true
L["<DEBUG> |r "] = true

--Output Strings from Core
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = true
L[" macros per character.  You currently have "] = true
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = true
L["/gs|r again."] = true
L["Close to Maximum Macros.|r  You can have a maximum of "] = true
L["|r.  You can also have a  maximum of "] = true
L[" macros per Account.  You currently have "] = true
L["Contributed by: "] = true
L["No Help Information "] = true
L["Unknown Author|r "] = true
L["|r Incomplete Sequence Definition - This sequence has no further information "] = true
L["Two sequences with unknown sources found."] = true
L["FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = true

-- Setup and Help Output from Core
L["GnomeSequencer was originally written by semlar of wowinterface.com."] = true
L["This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = true
L["Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = true
L["This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = true
L[":|r To get started "] = true
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = true
L["/gs listall|r will produce a list of all available macros with some help information."] = true
L["To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = true
L["The command "] = true
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = true
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = true
L[":|r Your current Specialisation is "] = true
L["  The Alternative ClassID is "] = true
L["GnomeSequencer-Enhanced loaded.|r  Type "] = true
L["/gs help|r to get started."] = true
L["Version="] = true
L[":|r You cannot delete the only copy of a sequence."] = true
L[" has been added as a new version and set to active.  Please review if this is as expected."] = true
L["A sequence collision has occured. "] = true
L[" tried to overwrite the version already loaded from "] = true
L[". This version was not loaded."] = true
L["Sequence specID set to current spec of "] = true
L["Sequence Author set to Unknown"] = true
L["No Help Information Available"] = true
L[" was imported with the following errors."] = true

-- 1.4 changes
L["No Active Version"] = true
L["Matching helpTxt"] = true
L["Different helpTxt"] = true
L["You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = true

--sequence editor stuff
L["Sequence"] = true
L["Edit"] = true
L["New"] = true
L["Choose Language"] = true
L["Translated Sequence"] = true
L["Sequence Viewer"] = true
L["Gnome Sequencer: Sequence Viewer"] = true
L["Load Sequence"] = true
L["Disable Sequence"] = true
L["Enable Sequence"] = true
L["Translate to"] = true
L["Sequence Editor"] = true
L["Gnome Sequencer: Sequence Editor."] = true
L["Sequence Name"] = true
L["Step Function"] = true
L["Sequential (1 2 3 4)"] = true
L["Priority List (1 12 123 1234)"] = true
L["Specialization Specific Macro"] = true
L["Classwide Macro"] = true
L["Macro Icon"] = true
L["KeyPress"] = true
L["KeyRelease"] = true
L["Completely New GS Macro."] = true
L["Please wait till you have left combat before using the Sequence Editor."] = true
L["The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "] = true
L["/gs |r to get started."] = true
L["Gnome Sequencer: Sequence Version Manager"] = true
L["Manage Versions"] = true
L["Active Version: "] = true
L["Select Other Version"] = true
L["Make Active"] = true
L["Delete Version"] = true
L["No Sequences present so none displayed in the list."] = true
L["Specialisation / Class ID"] = true
L["You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"] = true
-- options Debug


-- options stuff
L["You need to reload the User Interface to complete this task.  Would you like to do this now?"] = true
L["Yes"] = true
L["No"] = true
L["|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"] = true
L["General"] = true
L["General Options"] = true
L["Only Save Local Macros"] = true
L["GS-E can save all macros or only those versions that you have created locally.  Turning this off will cache all macros in your WTF\\GS-Core.lua variables file but will increase load times and potentially cause colissions."] = true
L["Use Macro Translator"] = true
L["The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."] = true
L["Delete Orphaned Macros on Logout"] = true
L["As GS-E is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gs cleanorphans"] = true
L["Use Global Account Macros"] = true
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = true
L["Set Default Icon QuestionMark"] = true
L["By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."] = true
L["Seed Initial Macro"] = true
L["If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."] = true
L["Gameplay Options"] = true
L["Require Target to use"] = true
L["This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."] = true
L["Prevent Sound Errors"] = true
L["This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Prevent UI Errors"] = true
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Clear Errors"] = true
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Use First Ring in KeyRelease"] = true
L["Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."] = true
L["Use Second Ring in KeyRelease"] = true
L["Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."] = true
L["Use First Trinket in KeyRelease"] = true
L["Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."] = true
L["Use Second Trinket in KeyRelease"] = true
L["Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."] = true
L["Use Neck Item in KeyRelease"] = true
L["Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."] = true
L["Use Belt Item in KeyRelease"] = true
L["Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."] = true
L["Debug Mode Options"] = true
L["Enable Mod Debug Mode"] = true
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = true
L["Display debug messages in Chat Window"] = true
L["This will display debug messages in the Chat window."] = true
L["Store Debug Messages"] = true
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = true
L["Debug Sequence Execution"] = true
L["Output the action for each button press to verify StepFunction and spell availability."] = true
L["Colour"] = true
L["Colour and Accessibility Options"] = true
L["Title Colour"] = true
L["Picks a Custom Colour for the Mod Names."] = true
L["Author Colour"] = true
L["Picks a Custom Colour for the Author."] = true
L["Command Colour"] = true
L["Picks a Custom Colour for the Commands."] = true
L["Emphasis Colour"] = true
L["Picks a Custom Colour for emphasis."] = true
L["Normal Colour"] = true
L["Picks a Custom Colour to be used normally."] = true
L["Editor Colours"] = true
L["Spell Colour"] = true
L["Picks a Custom Colour to be used for Spells and Abilities."] = true
L["Unknown Colour"] = true
L["Picks a Custom Colour to be used for unknown terms."] = true
L["Icon Colour"] = true
L["Picks a Custom Colour to be used for Icons."] = true
L["SpecID/ClassID Colour"] = true
L["Picks a Custom Colour to be used for numbers."] = true
L["String Colour"] = true
L["Picks a Custom Colour to be used for strings."] = true
L["Conditionals Colour"] = true
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = true
L["Help Colour"] = true
L["Picks a Custom Colour to be used for braces and indents."] = true
L["Step Functions"] = true
L["Picks a Custom Colour to be used for StepFunctions."] = true
L["Language Colour"] = true
L["Picks a Custom Colour to be used for language descriptors"] = true
L["Blizzard Functions Colour"] = true
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = true
L["Plugins"] = true
L["GS-E Plugins"] = true
L["Registered Addons"] = true
L["Available Addons"] = true
L[":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"] = true
L["Use Realtime Parsing"] = true
L["The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."] = true
L["Import"] = true
L["Close"] = true
L["Import Macro from Forums"] = true
L["Debug Output Options"] = true
L["Enable Debug for the following Modules"] = true
L["Debug"] = true
L["Filter Macro Selection"] = true
L["Show All Macros in Editor"] = true
L["By setting this value the Sequence Editor will show every macro for every class."] = true
L["Show Class Macros in Editor"] = true
L["By setting this value the Sequence Editor will show every macro for your class."] = true
L["Source Language "] = true
L[" is not available.  Unable to translate sequence "] = true
L["Target language "] = true
L["Auto Create Class Macro Stubs"] = true
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = true
L["Auto Create Global Macro Stubs"] = true
L["When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"] = true
L["Updating due to new version."] = true
L["Creating New Sequence."] = true

-- Transmission stuff
L["This will display debug messages for the GS-E Ingame Transmission and transfer"] = true

-- New Strings 1.4
L["Use Head Item in KeyRelease"] = true
L["Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."] = true
L["GS-E: Left Click to open the Sequence Editor"] = true
L["GS-E: Middle Click to open the Transmission Interface"] = true
L["GS-E: Right Click to open the Sequence Debugger"] = true
L["Sequence Debugger"] = true
L["Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"] = true
L["Output"] = true
L["Pause"] = true
L["Resume"] = true
L["Clear"] = true
L["Options"] = true
L["Disable"] = true
L["Enable"] = true
L["GnomeSequencer-Enhanced"] = true
L["Help Information"] = true
L["Save"] = true
L["Sequence Saved as version "] = true
L["Imported new sequence "] = true
L["Send To"] = true
L["Send"] = true
L["Received Sequence "] = true
L[" from "] = true
L[" saved as version "] = true
L["Ready to Send"] = true
L[" sent"] = true
L["Reset Macro when out of combat"] = true
L["Resets macros back to the initial state when out of combat."] = true
L["A sequence collision has occured.  Your local version of "] = true

-- 1.4.4
L["Inner Loop Start"] = true
L["Inner Loop End"] = true
L["Inner Loop Limit"] = true
L["Record Macro"] = true
L["Gnome Sequencer: Record your rotation to a macro."] = true
L["Actions"] = true
L["Record"] = true
L["Pause"] = true
L["Create Macro"] = true
L["Stop"] = true

-- 2.0
L["The Custom StepFunction Specified is not recognised and has been ignored."] = true
L["Load"] = true
L["There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"]= true
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = true
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = true
L["Macro unable to be imported."] = true
L["Macro Import Successful."]= true
L["Gnome Sequencer: Import a Macro String."] = true
L["GSE Macro"] = true
L["Legacy GS/GSE1 Macro"] = true
L["Macro Collection to Import."] = true
L["Configuration"] = true
L["Talents"] = true
L["Help Information"] = true
L["Help Link"] = true
L["Default Version"] = true
L["Raid"] = true
L["Mythic"] = true
L["PVP"] = true
L["Language"] = true
L["PreMacro"] = true
L["PostMacro"] = true
L["Author"] = true
L["Head"] = true
L["Neck"] = true
L["Belt"] = true
L["Ring 1"] = true
L["Ring 2"] = true
L["Trinket 1"] = true
L["Trinket 2"] = true
L["Use"] = true
L["Target"] = true
L["Combat"] = true
L["Resets"] = true
L["Sequence %s saved."] = true
L["This is the only version of this macro.  Delete the entire macro to delete this version."] = true
L["You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."] = true
L["Macro Version %d deleted."] = true
L["This change will not come into effect until you save this macro."] = true
L["PVP setting changed to Default."] = true
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = true
L["Delete"] = true
L["Cancel"] = true
L["Delete Icon"] = true
L["Create Icon"] = true
L["Addin Version %s contained versions for the following macros: \n%s"] = true
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = true
L["The Sample Macros have been reloaded."] = true
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = true
L["GSE"] = true
L["/gs |r to get started."] = true
L["Gnome Sequencer: Export a Sequence String."] = true
L["Export a Sequence"] = true
L["Export"] = true
L["Help URL"] = true
L["Copy this link and open it in a Browser."] = true
L["This will display debug messages for the "] = true
L[" Deleted Orphaned Macro "] = true

--- GSE2.0.1-2.0.4
L["Create buttons for Global Macros"] = true
L["Global Macros are those that are valid for all classes.  GSE2 also imports unknown macros as Global.  This option will create a button for these macros so they can be called for any class.  Having all macros in this space is a performance loss hence having them saved with a the right specialisation is important."] = true
L["Show Global Macros in Editor"] = true
L["This shows the Global Macros available as well as those for your class."] = true
L["Moved %s to class %s."] = true
L["Your current Specialisation is "] = true
