---@diagnostic disable: undefined-global, duplicate-set-field
-- End-to-end CBOR transport test, entirely in Lua: the Node encoder
-- (api/src/lib/cbor.js) emits the delta as CBOR; here we decode it with a
-- pure-Lua CBOR decoder (spec/cbor.lua, a stand-in for the Mod's
-- C_EncodingUtil.DeserializeCBOR) and apply it via GSE.ApplySequenceDelta.
-- Fixtures (spec/seqdelta_cbor_fixtures.lua) are AUTO-GENERATED by the Node
-- encoder, so this pins Node-encode ↔ Lua-decode ↔ apply agreement.
--
-- Run with: busted spec/cbordelta_spec.lua

require("../spec/mockGSE")
require("../GSE/API/SequenceDelta")
local cbor = require("../spec/cbor")

-- bytes from a hex string, for the RFC 8949 vector checks
local function fromhex(h)
  return (h:gsub("..", function(cc) return string.char(tonumber(cc, 16)) end))
end

describe("CBOR decoder (RFC 8949 Appendix A vectors)", function()
  it("decodes the canonical integer/string/array/map/simple vectors", function()
    assert.are.equal(0, cbor.decode(fromhex("00")))
    assert.are.equal(23, cbor.decode(fromhex("17")))
    assert.are.equal(24, cbor.decode(fromhex("1818")))
    assert.are.equal(1000, cbor.decode(fromhex("1903e8")))
    assert.are.equal(-1, cbor.decode(fromhex("20")))
    assert.are.equal(-100, cbor.decode(fromhex("3863")))
    assert.are.equal("IETF", cbor.decode(fromhex("6449455446")))
    assert.are.same({ 1, 2, 3 }, cbor.decode(fromhex("83010203")))
    assert.are.same({ a = 1, b = { 2, 3 } }, cbor.decode(fromhex("a26161016162820203")))
    assert.are.equal(false, cbor.decode(fromhex("f4")))
    assert.are.equal(true, cbor.decode(fromhex("f5")))
    assert.is_nil(cbor.decode(fromhex("f6")))
  end)

  it("decodes integer map keys to NUMBER keys (Mod-native form)", function()
    -- map {1:"x", "Type":"Action"} as the Node encoder emits it
    local t = cbor.decode(fromhex("a2016178645479706566416374696f6e"))
    assert.are.equal("x", t[1])          -- number key, not "1"
    assert.are.equal("Action", t.Type)
  end)
end)

describe("CBOR delta transport (Node encode -> Lua decode -> apply)", function()
  local fixtures = require("../spec/seqdelta_cbor_fixtures")

  for _, fx in ipairs(fixtures) do
    it("round-trips: " .. fx.name, function()
      local delta = cbor.decode(fx.cbor)
      local out = GSE.ApplySequenceDelta(fx.base, delta)
      assert.are.same(fx.expected, out)
    end)
  end
end)
