local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    [[Shane Kuchler]],
    [[Stuart Hendrie]],
    [[Luke Beals]],
    [[Samuel Lacerda]],
    [[John D Aulbu]],
    [[Stefan Hauck]],
    [[Travis Delaney]],
    [[Eric Stoeckel Jr]],
    [[Unktehila Iksar]],
    [[Jakob Andersen]],
    [[Jeff Butler]],
    [[Mathusala]],
    [[Aiden Gramson]],
    [[TwistedSMF ]],
    [[Christian Mostert]],
    [[RACHEL liperote]],
    [[Tommy ]],
    [[wouZAR ]],
    [[William Smith]],
    [[Calvin Jones]],
    [[Keith Fults]],
    [[Charles R Tabor]],
    [[wynne clark]],
    [[Laura A Clegg]],
    [[Wizard Hayden]],
    [[Dieter Cazon]],
    [[jamie bradley]],
    [[Andrew Lester]],
    [[Anthony Lutke]],
    [[Bryan Seitz]],
    [[Melchy]],
    [[Junior Rodriguez]],
    [[Cruelier]],
    [[Anthony]],
    [[Michael Mcdaniels]],
    [[Ken McCune]],
    [[Jonathan Devore Scales]],
    [[Patrick O'Hagan]],
    [[Laura Sieloff]],
    [[quoc nguyen]],
    [[Corey Marchant]],
    [[Dustin Gadd]],
    [[Sol LeTaire]],
    [[Thomas Rambaut]],
    [[Daniel Thomas]],
    [[TorbjÃ¶rn JÃ¶nsson]],
    [[Billy ]],
    [[Baely ]],
    [[Adam Fisher]],
    [[Brian Lynch]],
    [[Jamie Cuomo]],
    [[Henrik Nielsen]],
    [[Scotty]],
    [[Scott Penney]],
    [[ffcjonny]],
    [[Erin Reymann]],
    [[Sparrowhawk Sr]],
    [[A Four]],
    [[Jason ]],
    [[DMFerree]],
    [[lloyd spencer]],
    [[Bengt Grahl]],
    [[Martin Vines]],
    [[Jennifer Angelidis]],
    [[Lars Wingemark]],
    [[Walter Beiter]],
    [[Nancy Pierson]],
    [[Chris Bunting]],
    [[DENNIS CHRISTENSEN]],
    [[David Rose]],
    [[Adam Tall]],
    [[Rakuza yoknomu]],
    [[rightonetwo]],
    [[Kevin Ibrahim]],
    [[Paul Guertin]],
    [[David Rice]],
    [[Jason Johnson]],
    [[Hollis Ford]],
    [[William Lee]],
    [[curtis buffum]],
    [[Mark ]],
    [[Alejandro Sanclemente]],
    [[Penny2]],
    [[Mark Bradley]],
    [[DJ]],
    [[James Blamey]],
    [[David Isburgh]],
    [[Naomi McMillan]],
    [[Marc allen]],
    [[Eric Rainey]],
    [[Brian Dickerson]],
    [[Fallens Death]],
    [[Randy Barton]],
    [[Kenny Pritchard]],
    [[Raymond Monk]],
    [[Bromdor]],
    [[Mardy Stevens]],
    [[Bghy Rbfch]],
    [[Ricky Woods]],
    [[Robert Costello]],
    [[John Martin]],
    [[Stew Frei]],
    [[KURT MOSS]],
    [[Paul Kingman]],
    [[Karoldue ]],
    [[Daniel Perez]],
    [[Binary Nick]],
    [[Matthew Jenner]],
    [[Toto Leo]],
    [[Nimmerland Gaming [NlG] Brainz]],
    [['William Meringolo]],
    [[Daniel SÃ¼mmchen]],
    [[Eric Roberts]],
    [[Denis Samoilov]],
    [[Khoa Truong]],
    [[impaxx ]],
    [[Scott Davis]],
    [[Adventures Of Raven]],
    [[FERDIN GONZALEZ]],
    [[Brian]],
    [[Fangorian_1337]],
    [[Zoonets]],
    [[Roberto Roeschmann]],
    [[Renato Freitas]],
    [[Michael Schulz]],
    [[Goregoth]],
    [[Larry Hook]],
    [[MVP]],
    [[Randy G]],
    [[Eric Sanders]],
    [[Anubikk ]],
    [[Jerry T]],
    [[neofodder]],
    [[Randy Rushing]],
    [[Victor Hodges]],
    [[Mephiroth]],
    [[Samuel Spencer]],
    [[Nora Kirschling]],
    [[Keith Kelly]],
    [[Robin Laubinger]],
    [[Andrew Baldwin]],
    [[T D]],
    [[Christopher Lee]],
    [[Ouya France]],
    [[Jon Noland]],
    [[Kevin James]],
    [[Peter von der Ahe]],
    [[Dennis Jakobsen]],
    [[Holger]],
    [[mourad abrahim]],
    [[Schiwouna Schi]],
    [[Eric Vincent]],
    [[Rhaina]],
    [[John Beland]],
    [[twmwalters]],
    [[TwiztidBloom]],
    [[Shaun Baxter]],
    [[Nicholas Brown]],
    [[DJ_FingaGunz]],
    [[Steve Clink]],
    [[Bearded_Gamer ]],
    [[Allan Smith Nielsen]],
    [[Jeremy Jones]],
    [[Eznoda]],
    [[Leprona]],
    [[Possum Jenkins]],
    [[Ashley Ludwig]],
    [[Johan Lindqvist]],
    [[Luke Newland]],
    [[Ryo]],
    [[Mitchell Emberson]],
    [[Codda Matl]],
    [[Tawaporah]],
    [[mike saul]],
    [[Lara Marcattili]],
    [[Kyle Francis]],
    [[david hawke]],
    [[Robert Wears]],
    [[The world through my eyes]],
    [[Thomas Maurdal]],
    [[Stephen Seagrave]],
    [[Everett St.Clair]],
    [[pantinhatv]],
    [[Drioz]],
    [[Charles]],
    [[pascalmaramis]],
    [[Gustav Gans]],
    [[Melissa N Anderson]],
    [[ralf heckel]],
    [[Scarlett Knight]],
    [[Jeremy Grayson]],
    [[Nebiros]],
    [[Glenn van Kooijk]],
    [[Robert Webb]],
    [[Kristopher Bowling]],
    [[ale diki]],
    [[Sternwind]],
    [[Chris Juengel]],
    [[Gerald McCandless]],
    [[Aaron Steley]],
    [[MolarMacros]],
    [[Mark van de Beek]],
    [[Kickn Chickn]],
    [[Ashley]],
    [[alan coutts]],
    [[Jerrod Linderman]],
    [[kelly jarrell]],
    [[Dredd]],
    [[Kemal Tolun]],
    [[Daniel Kristofersson]],
    [[Jamie Currier]],
    [[Baka Pixel]],
    [[Chris Livingston]],
    [[Adaestra ]],
    [[Jeffrey White]],
    [[Ferat A]],
    [[Beta]],
    [[Dan Inda]],
    [[Andris Kulmans]],
    [[Chris Esparza]],
    [[Jodi Meese]],
    [[Laurie Holmes]],
    [[Steven Hansen]],
    [[Fadi Alfadda]],
    [[Rene Traue]],
    [[Mikkel Juul JÃ¸rgensen]],
    [[Eric Desmarais]],
    [[Mike Pegg]],
    [[Eric donini]],
    [[beat theory]],
    [[Dustin Davenport]],
    [[Mark]],
    [[evasion]],
    [[James Faircloth]],
    [[Kal basra]],
    [[zibiken]],
    [[Marco Petraszczuk]],
    [[Toril Harink ]],
    [[Michael Swancott]],
    [[Pippa Martel]],
    [[Ray Feliciano]],
    [[BRIAN V DELLER]],
    [[ryan kloepper]],
    [[Jed Lawton]],
    [[Simon Wilcock]],
    [[Ivan Chiu]],
    [[UhohOreo ]],
    [[Jani Kay]],
    [[Luis Flores]],
    [[Brian Miller]],
    [[Radioactive Bullfrog]],
    [[Dominik Krabacher]],
    [[sten]],
    [[Enmity]],
    [[Jessica]],
    [[Tamer Baes]],
    [[Randall Crank]],
    [[chris ogle]],
    [[Deborah Gough]],
    [[bk]],
    [[Sebastian Kieback]],
    [[xManiac]],
    [[kay rennow]],
    [[Andrew VanArman]],
    [[Adam Doherty]],
    [[Kevin Hare]],
    [[Warren Jumper]],
    [[Jack Selektion]],
    [[Roger Heiniluoma]],
    [[Joseph Lowery]],
    [[Jim B]],
    [[Tim Weiden]],
    [[Gendi]],
    [[Herbert Besenfelder]],
    [[Tommy Southam]],
    [[Razerwing]],
    [[Gary]],
    [[Mark Robinson]],
    [[Angrypug]],
    [[Scott Rose]],
    [[James Beck]],
    [[luc janssens]],
    [[Oliver Berger]],
    [[Gáº¥u Panda]],
    [[Ryan Hickey]],
    [[E Peters]],
    [[Ashneel Kumar]],
    [[Tsaiko]],
    [[Jasper Hengefeld]],
    [[friedbones]],
    [[Grumpy British old Gamer]],
    [[Meph]],
    [[Macroholic]],
    [[Kiel Arenas]],
    [[Kevin Fellion]],
    [[Gary Markland]],
    [[William P Grady]],
    [[Isaiah Lombardy]],
    [[ARTEX]],
    [[Bob]],
    [[giorgino]],
    [[jay garcia]],
    [[Angel Marchini]],
    [[Diedora]],
    [[Euben Hadd]],
    [[Chris Cordwell]],
    [[Caleb]],
    [[Jacob Richey]],
    [[Misty Jinn]],
    [[Gianluca Berian]],
    [[Martin Needham]],
    [[Andrew Fox]],
    [[kristian montevecchi]],
    [[Sean-Heidi Serraguard]],
    [[900obzen ]],
    [[W Wilson]],
    [[Andy Erickson]],
    [[Ben Hocking]],
    [[Emanuel Barbi]],
    [[Scott Flippo]],
    [[Tabby Post]],
    [[Jeff Hughes]],
    [[Tom Straugh]],
    [[Susan Mushill]],
    [[LivinOnTheCorner]],
    [[Hannah Mae]],
    [[ttplank]],
    [[Aaron Smith]],
    [[Spencer Blomquist]],
    [[Andre Carbonell]],
    [[Shtev]],
    [[Michael Irving]],
    [[Ernest Dolby]],
    [[Mercurio]],
    [[Deezyl Fizzlepop]],
    [[George McCubbins]],
    [[Elfyau]],
    [[Supbear ]],
    [[Steven Shaw]],
    [[Thore Kvalheim]],
    [[Russell Baker]],
    [[Ray Adams]]
}
